name: Build GlucoseDirect
run-name: Build GlucoseDirect (${{ github.ref_name }})

on:
  workflow_dispatch: # Triggered manually
  schedule:
    - cron: "0 8 * * 3" # Check for updates and build every Wednesday at 08:00 UTC
    - cron: "0 6 1 * *" # Build on the 1st of every month at 06:00 UTC

jobs:
  build_glucosedirect:
    name: Build GlucoseDirect
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Java (required for Android builds)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 2: Install Android SDK and Build Tools
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3
          ndk-version: 21.4.7075529

      # Step 3: Clone the GlucoseDirect repository
      - name: Clone GlucoseDirect repository
        run: |
          git clone https://github.com/lutzlukesch/GlucoseDirect.git GlucoseDirect
          cd GlucoseDirect
          git checkout main

      # Step 4: Build the GlucoseDirect app
      - name: Build GlucoseDirect APK
        run: |
          cd GlucoseDirect
          ./gradlew assembleRelease

      # Step 5: Upload APK as an artifact for download
      - name: Upload GlucoseDirect APK
        uses: actions/upload-artifact@v4
        with:
          name: glucose-direct-apk
          path: |
            GlucoseDirect/app/build/outputs/apk/release/app-release.apk
